import { test, expect } from '@playwright/test';
import { PDFDocument } from 'pdf-lib';
import JSZip from 'jszip';
import { readFileSync } from 'node:fs';

test('author workflow: edit, save, reopen, checkpoint, publish, and restore', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/editor');
  await expect(page.getByRole('button', { name: /Open sample book/ })).toBeVisible();
  await page.screenshot({ path: 'artifacts/studio-library.png', fullPage: true });
  await page.getByRole('button', { name: /Open sample book/ }).click();
  await expect(page.getByLabel('Chapter content')).toContainText('The first thing I noticed');
  await page.getByLabel('Book title', { exact: true }).fill('A Book Worth Keeping');
  await page.getByLabel('Author name').fill('Test Author');
  await page.getByLabel('Chapter content').click();
  await page.keyboard.press('Control+End');
  await page.keyboard.type(' A sentence that must survive reopening.');
  await expect(page.getByText('Saved on this device', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'artifacts/studio-workspace.png', fullPage: true });
  await page.getByLabel('Version history').click();
  await page.getByRole('button', { name: 'Save checkpoint' }).click();
  await expect(page.locator('.studio-notice')).toContainText('Checkpoint saved');
  await page.getByLabel('Back to library').click();
  await page.reload();
  await page.getByRole('button', { name: /A Book Worth Keeping/ }).click();
  await expect(page.getByLabel('Chapter content')).toContainText('A sentence that must survive reopening.');
  await page.getByRole('button', { name: 'Design', exact: true }).click();
  await expect(page.getByText(/measured pages/)).toBeVisible({ timeout: 60000 });
  await expect(page.locator('iframe[title="Book spread"]')).toBeVisible();
  await page.getByRole('tab', { name: 'Print' }).click();
  const frame = page.frameLocator('iframe[title="Measured book preview"]');
  await expect(frame.locator('.pagedjs_page')).not.toHaveCount(0);
  const previewPages = await frame.locator('.pagedjs_page').count();
  expect(await frame.locator('.pagedjs_page').first().evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(255, 255, 255)');
  await expect.poll(async () => frame.locator('.pagedjs_pages #section-1').evaluate(el => {
    const top = el.closest('.pagedjs_page')!.getBoundingClientRect().top;
    return top >= 0 && top < 100;
  })).toBe(true);
  await page.screenshot({ path: 'artifacts/studio-design.png', fullPage: true });
  await page.getByRole('button', { name: 'Export book', exact: true }).click();
  const epubDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: /Reading edition/ }).click();
  const epub = await epubDownload; await epub.saveAs('artifacts/test-book.epub');
  const fs = await import('node:fs/promises');
  const zip = await JSZip.loadAsync(await fs.readFile('artifacts/test-book.epub'));
  expect(await zip.file('EPUB/package.opf')!.async('string')).toContain('Test Author');
  expect(await zip.file('EPUB/section-1.xhtml')!.async('string')).toContain('A sentence that must survive reopening.');
  const backupDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download editable project' }).click();
  const backup = await backupDownload; await backup.saveAs('artifacts/test-book.booksane');
  const pdfDownload = page.waitForEvent('download', { timeout: 90000 });
  await page.getByRole('button', { name: /^Print interior · PDF Measured/ }).click();
  const pdf = await pdfDownload; await pdf.saveAs('artifacts/test-book.pdf');
  const document = await PDFDocument.load(await fs.readFile('artifacts/test-book.pdf'));
  expect(document.getPageCount()).toBeGreaterThan(3);
  expect(document.getPageCount()).toBe(previewPages);
  expect(document.getPage(0).getWidth()).toBeCloseTo(432, 0);
  expect(document.getPage(0).getHeight()).toBeCloseTo(648, 0);
  const pdfx = page.getByRole('button', { name: /Print interior · PDF\/X-1a/ });
  if (await pdfx.count()) {
    const xDownload = page.waitForEvent('download', { timeout: 120000 });
    await pdfx.click();
    const x = await xDownload; await x.saveAs('artifacts/test-book-pdfx.pdf');
    const bytes = await fs.readFile('artifacts/test-book-pdfx.pdf');
    expect(bytes.subarray(0, 8).toString()).toBe('%PDF-1.3');
    expect(bytes.toString('latin1')).toContain('GTS_PDFX');
    expect((await PDFDocument.load(bytes)).getPageCount()).toBe(previewPages);
  }
  await page.getByLabel('Close export').click();
  await page.getByLabel('Back to library').click();
  await page.locator('input[type=file]').first().setInputFiles('artifacts/test-book.booksane');
  await expect(page.getByLabel('Book title', { exact: true })).toHaveValue('A Book Worth Keeping');
  await expect(page.getByLabel('Chapter content')).toContainText('A sentence that must survive reopening.');
  expect(errors).toEqual([]);
});

test('blank books and section operations preserve rich text', async ({ page }) => {
  await page.goto('/editor');
  await page.getByRole('button', { name: 'Create a book' }).click();
  await page.getByRole('button', { name: 'Start writing', exact: true }).click();
  await expect(page.getByLabel('Chapter content')).toHaveText('');
  await page.getByLabel('Chapter content').fill('Words with meaning');
  await page.getByLabel('Chapter content').press('Control+A');
  await page.getByRole('button', { name: 'Bold', exact: true }).click();
  await expect(page.locator('.manuscript-prose strong')).toContainText('Words with meaning');
  await page.getByLabel('Duplicate section').click();
  await expect(page.getByLabel('Chapter content')).toContainText('Words with meaning');
  await expect(page.locator('.manuscript-prose strong')).toContainText('Words with meaning');
  await page.getByLabel('Add chapter', { exact: true }).click();
  await page.getByLabel('Section title').fill('A new chapter');
  await page.getByLabel('Chapter content').fill('New chapter body');
  await page.getByLabel('Move section up').click();
  await page.getByLabel('Back to library').click();
  await page.reload();
  await page.getByRole('button', { name: /Untitled book/ }).click();
  await page.getByRole('button', { name: /A new chapter/ }).click();
  await expect(page.getByLabel('Chapter content')).toContainText('New chapter body');
});

test('DOCX import retains headings, emphasis, and tables, with a review report', async ({ page }) => {
  const zip = new JSZip();
  zip.file('[Content_Types].xml', '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');
  zip.file('_rels/.rels', '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');
  zip.file('word/styles.xml', '<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/></w:style></w:styles>');
  zip.file('word/document.xml', '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>Chapter One</w:t></w:r></w:p><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Important words preserved</w:t></w:r></w:p><w:tbl><w:tr><w:tc><w:p><w:r><w:t>Cell content</w:t></w:r></w:p></w:tc></w:tr></w:tbl></w:body></w:document>');
  await page.goto('/editor');
  await expect(page.getByRole('button', { name: /Open sample book/ })).toBeVisible();
  await page.locator('input[type=file]').first().setInputFiles({ name: 'Structured.docx', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', buffer: await zip.generateAsync({ type: 'nodebuffer' }) });
  await expect(page.getByRole('dialog', { name: 'Import report' })).toBeVisible();
  await page.getByRole('button', { name: 'See my book' }).click();
  await expect(page.locator('.manuscript-prose strong')).toContainText('Important words preserved');
  await expect(page.locator('.manuscript-prose table')).toContainText('Cell content');
});

test('a messy manuscript is cleaned on import and each fix can be undone', async ({ page }) => {
  await page.goto('/editor');
  await expect(page.getByRole('button', { name: /Open sample book/ })).toBeVisible();
  const messy = 'My Book\n\nCHAPTER ONE: THE DEPARTURE\n\nShe said "it\'s late" and left--quickly...\n\n\n\n***\n\nThe  road  was long.\n\nCHAPTER 2\n\nThey came home.';
  await page.locator('input[type=file]').first().setInputFiles({ name: 'Messy.txt', mimeType: 'text/plain', buffer: Buffer.from(messy) });
  const dialog = page.getByRole('dialog', { name: 'Import report' });
  await expect(dialog).toContainText(/I cleaned up \d+ things/);
  await page.waitForTimeout(800);
  await page.screenshot({ path: 'artifacts/tidy-dialog.png' });
  const quotes = dialog.getByRole('switch', { name: /quote/i });
  await quotes.click();
  await expect(quotes).toHaveAttribute('aria-checked', 'false');
  await quotes.click();
  await dialog.getByRole('button', { name: 'See my book' }).click();
  await expect(page.getByText('The Departure', { exact: true }).first()).toBeVisible();
  await expect(page.getByLabel('Chapter content')).toContainText('She said “it’s late” and left—quickly…');
});

test('mobile library and workspace remain usable without page-level horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/editor');
  await expect(page.getByRole('button', { name: 'Create a book' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: /Open sample book/ }).click();
  await expect(page.getByLabel('Chapter content')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/studio-mobile.png', fullPage: true });
});

test('long manuscript composes across pages and responds to trim changes', async ({ page }) => {
  await page.goto('/editor');
  await expect(page.getByRole('button', { name: /Open sample book/ })).toBeVisible();
  const paragraph = 'Attention gives ordinary moments their shape. We notice the light at the window, the rhythm of a familiar street, and the stories carried by people around us. A book preserves those discoveries for another reader, who brings an entirely different life to the page.';
  const manuscript = 'Chapter One\n\n' + Array(220).fill(paragraph).join('\n\n') + '\n\nChapter Two\n\n' + Array(220).fill(paragraph).join('\n\n');
  await page.locator('input[type=file]').first().setInputFiles({ name: 'Long manuscript.txt', mimeType: 'text/plain', buffer: Buffer.from(manuscript) });
  await page.getByRole('button', { name: 'See my book' }).click();
  await page.getByRole('button', { name: 'Design', exact: true }).click();
  await expect(page.getByText(/measured pages/)).toBeVisible({ timeout: 90000 });
  const frame = page.frameLocator('iframe[title="Measured book preview"]');
  const largeTrimPages = await frame.locator('.pagedjs_page').count();
  expect(largeTrimPages).toBeGreaterThan(30);
  await page.getByLabel('Trim size').selectOption('5x8');
  await expect(page.getByText(/measured pages.*5 × 8/)).toBeVisible({ timeout: 90000 });
  expect(await frame.locator('.pagedjs_page').count()).toBeGreaterThan(largeTrimPages);
});


test('first-book onboarding explains choices, creates a named book, and provides optional help', async ({ page }) => {
  await page.goto('/editor');
  await expect(page.getByRole('heading', { name: 'Let’s make your first book.' })).toBeVisible();
  await expect(page.getByRole('list', { name: 'The publishing workflow' })).toBeVisible();
  await page.screenshot({ path: 'artifacts/onboarding-start.png', fullPage: true });
  await page.getByRole('button', { name: 'Create a book', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Every book starts somewhere.' })).toBeVisible();
  await expect(page.getByLabel('Working title')).toBeFocused();
  await page.getByLabel('Working title').fill('My First Book');
  await page.getByLabel('Setup author name').fill('A New Author');
  await page.screenshot({ path: 'artifacts/onboarding-setup.png', fullPage: true });
  await page.getByRole('button', { name: 'Start writing', exact: true }).click();
  await expect(page.getByLabel('Book title', { exact: true })).toHaveValue('My First Book');
  await expect(page.getByLabel('Author name')).toHaveValue('A New Author');
  await expect(page.getByRole('region', { name: 'Next step guidance' })).toBeVisible();
  await expect(page.getByLabel('Trim size')).toBeHidden();
  await page.getByLabel('Chapter content').fill('My first sentence belongs to me.');
  await page.screenshot({ path: 'artifacts/onboarding-writing.png', fullPage: true });
  await page.getByLabel('Hide getting-started guidance').click();
  await expect(page.getByRole('region', { name: 'Next step guidance' })).toHaveCount(0);
  await page.getByLabel('Getting started help').click();
  await expect(page.getByRole('dialog', { name: 'One book. Three simple stages.' })).toBeVisible();
  await page.getByRole('button', { name: /Design & preview Choose/ }).click();
  await expect(page.getByLabel('Trim size')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Literary theme' })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Modern theme' }).click();
  await expect(page.getByRole('button', { name: 'Modern theme' })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByText(/measured pages/)).toBeVisible({ timeout: 60000 });
  await page.screenshot({ path: 'artifacts/onboarding-design.png', fullPage: true });
  await expect(page.getByLabel('Type size')).toBeVisible();
});

test('import onboarding is keyboard-dismissable and clearly explains file preparation', async ({ page }) => {
  await page.goto('/editor');
  await page.getByRole('button', { name: 'Import manuscript', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Bring your words.' })).toBeVisible();
  await expect(page.getByText('For the cleanest Word import')).toBeVisible();
  await page.screenshot({ path: 'artifacts/onboarding-import.png', fullPage: true });
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Import manuscript', exact: true })).toBeFocused();
  await page.getByRole('button', { name: 'Import manuscript', exact: true }).click();
  const fileChooser = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: /Drop a file here, or choose a file/ }).click();
  await (await fileChooser).setFiles({ name: 'First manuscript.txt', mimeType: 'text/plain', buffer: Buffer.from('Chapter One\n\nWords brought through the guided import flow.') });
  await expect(page.getByRole('dialog', { name: 'Import report' })).toBeVisible();
  await page.getByRole('button', { name: 'See my book' }).click();
  await expect(page.getByLabel('Chapter content')).toContainText('Words brought through the guided import flow.');
});

test('new tools: parts, find and replace, publishing details, device preview and cover size', async ({ page }) => {
  await page.goto('/editor');
  await page.getByRole('button', { name: /Open sample book/ }).click();
  await expect(page.getByLabel('Chapter content')).toBeVisible();
  await page.getByRole('button', { name: 'Add part' }).click();
  await expect(page.locator('.section-item.is-part')).toHaveCount(1);
  await page.getByRole('button', { name: 'Find and replace' }).click();
  await page.getByLabel('Find text').fill('kettle');
  await expect(page.getByText('1 match in this book')).toBeVisible();
  await page.getByLabel('Replace with').fill('teapot');
  await page.getByRole('button', { name: 'Replace all' }).click();
  await expect(page.getByText('Replaced 1 match.')).toBeVisible();
  await page.getByText('Series and other books').click();
  await page.getByLabel('Also by').fill('The Quiet Year\nSmall Rooms');
  await expect(page.getByRole('button', { name: 'Callout box' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Footnote' })).toBeVisible();
  await page.getByRole('button', { name: 'Design', exact: true }).click();
  await page.getByRole('tab', { name: 'eBook' }).click();
  await page.getByRole('button', { name: 'Kindle' }).click();
  await page.getByRole('button', { name: 'Sepia' }).click();
  const ebook = page.frameLocator('iframe[title="eBook preview"]');
  await expect(ebook.getByText('Also by Alex Morgan')).toBeVisible();
  await expect(ebook.getByText('teapot', { exact: false })).toBeVisible();
  await expect(page.getByText(/Spine width/)).toBeVisible({ timeout: 60000 });
  await page.getByRole('button', { name: 'Hardcover' }).click();
  await expect(page.getByText('Spine hinge')).toBeVisible();
  await page.screenshot({ path: 'artifacts/new-tools.png', fullPage: true });
});

test('cover studio: designed front, full wrap with barcode, 3D, and downloads', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/editor');
  await page.getByRole('button', { name: /Open sample book/ }).click();
  await page.getByRole('button', { name: 'Cover', exact: true }).click();
  const preview = page.getByRole('img', { name: 'Front cover preview' });
  await expect(preview).toBeVisible();
  await expect.poll(() => preview.evaluate((c: HTMLCanvasElement) => c.width)).toBe(1600);
  await page.getByRole('button', { name: 'Arch' }).click();
  await page.getByRole('radio', { name: 'Colours 4' }).click();
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'artifacts/cover-front.png' });
  await page.getByLabel('Back cover blurb').fill('A quiet book about noticing. Twelve short essays on light, streets, neighbours and the stories we carry.\n\nFor anyone who has ever stopped to look.');
  await page.getByLabel('About the author').fill('Alex Morgan writes about everyday life and the things we notice when we slow down.');
  await page.getByLabel('ISBN').fill('978-0-306-40615-7');
  await expect(page.getByText('Barcode added')).toBeVisible();
  await page.getByRole('tab', { name: 'Full cover' }).click();
  await expect(page.getByText(/pages · spine/)).toBeVisible({ timeout: 90000 });
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'artifacts/cover-wrap.png' });
  const pdf = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Print cover · PDF' }).click();
  const pdfFile = await pdf;
  expect(pdfFile.suggestedFilename()).toMatch(/print-cover-kdp\.pdf$/);
  const coverPdf = await PDFDocument.load(readFileSync(await pdfFile.path()));
  const size = coverPdf.getPage(0).getSize();
  expect(size.height).toBeCloseTo(9.25 * 72, 1);
  expect(size.width).toBeCloseTo((0.25 + 12 + 24 * 0.002252) * 72, 1);
  const jpg = page.waitForEvent('download');
  await page.getByRole('button', { name: 'eBook cover · JPG' }).click();
  expect((await jpg).suggestedFilename()).toMatch(/ebook-cover\.jpg$/);
  await page.getByRole('tab', { name: '3D' }).click();
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'artifacts/cover-3d.png' });
  // the cover reaches the library shelf
  await page.waitForTimeout(1200);
  await page.getByRole('button', { name: 'Back to library' }).click();
  await expect(page.locator('.lib-cover.has-art img').first()).toBeVisible();
  await page.screenshot({ path: 'artifacts/cover-library.png' });
});

test('an uploaded cover is checked for each store', async ({ page }) => {
  await page.goto('/editor');
  await page.getByRole('button', { name: /Open sample book/ }).click();
  await page.getByRole('button', { name: 'Cover', exact: true }).click();
  const png = await page.evaluate(() => { const c = document.createElement('canvas'); c.width = 400; c.height = 640; const x = c.getContext('2d')!; x.fillStyle = '#7a3e5d'; x.fillRect(0, 0, 400, 640); return c.toDataURL('image/png').split(',')[1]; });
  await page.getByLabel('Upload cover image').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') });
  await expect(page.getByText('Too small for Kindle. It needs at least 500 px across; yours is 400.')).toBeVisible();
  await expect(page.getByText('Kindle shape (1 : 1.6).')).toBeVisible();
  await expect.poll(() => page.getByRole('img', { name: 'Front cover preview' }).evaluate((c: HTMLCanvasElement) => c.width)).toBe(400);
});
